export const mockHorses = [
  {
    id: 1,
    name: 'ディープインパクト',
    name_en: 'Deep Impact',
    born_year: 2002,
    sex: '牡',
    color: '鹿毛',
    status: '種牡馬',
    farm: '社台ファーム',
    birthplace: '北海道千歳市',
    trainer: '池江泰郎',
    stable: '栗東',
    owner: '金子真人ホールディングス',
    jockey: '武豊',
    sire: 'サンデーサイレンス',
    dam: 'ウインドインハーヘア',
    sire_of_sire: 'Halo',
    dam_of_sire: 'Wishing Well',
    sire_of_dam: 'Alzao',
    dam_of_dam: 'Burghclere',
    best_time: '2:23.3',
    best_distance: '3000m',
    best_race: '菊花賞',
    earnings: 1173667000,
    g1_wins: 7,
    win_rate: 87,
    record: { wins: 14, losses: 1, places: 0 },
    titles: ['皐月賞', '日本ダービー', '菊花賞', '有馬記念', '宝塚記念', '天皇賞（春）', 'ジャパンカップ'],
    races: [
      { id: 1, date: '2006-03-26', race_name: '阪神大賞典', grade: 'G2', position: 1, jockey: '武豊', time: '3:04.6', distance: '3000m', course: '阪神', prize: 66000000 },
      { id: 2, date: '2006-05-28', race_name: '天皇賞（春）', grade: 'G1', position: 1, jockey: '武豊', time: '3:13.4', distance: '3200m', course: '京都', prize: 130000000 },
      { id: 3, date: '2006-07-02', race_name: '宝塚記念', grade: 'G1', position: 1, jockey: '武豊', time: '2:11.7', distance: '2200m', course: '阪神', prize: 110000000 },
      { id: 4, date: '2006-11-26', race_name: 'ジャパンカップ', grade: 'G1', position: 1, jockey: '武豊', time: '2:25.1', distance: '2400m', course: '東京', prize: 250000000 },
      { id: 5, date: '2006-12-24', race_name: '有馬記念', grade: 'G1', position: 1, jockey: '武豊', time: '2:31.9', distance: '2500m', course: '中山', prize: 300000000 },
    ]
  },
  {
    id: 2,
    name: 'オルフェーヴル',
    name_en: 'Orfevre',
    born_year: 2008,
    sex: '牡',
    color: '栗毛',
    status: '種牡馬',
    farm: '社台ファーム',
    birthplace: '北海道千歳市',
    trainer: '池江泰寿',
    stable: '栗東',
    owner: '(有)サンデーレーシング',
    jockey: '池添謙一',
    sire: 'ステイゴールド',
    dam: 'オリエンタルアート',
    sire_of_sire: 'サンデーサイレンス',
    dam_of_sire: 'ゴールデンサッシュ',
    sire_of_dam: 'メジロマックイーン',
    dam_of_dam: 'エレクトロアート',
    best_time: '2:30.5',
    best_distance: '2500m',
    best_race: '有馬記念',
    earnings: 1107700000,
    g1_wins: 6,
    win_rate: 73,
    record: { wins: 11, losses: 3, places: 3 },
    titles: ['皐月賞', '日本ダービー', '菊花賞', '有馬記念(2回)', '宝塚記念'],
    races: [
      { id: 1, date: '2011-10-23', race_name: '菊花賞', grade: 'G1', position: 1, jockey: '池添謙一', time: '3:02.8', distance: '3000m', course: '京都', prize: 130000000 },
      { id: 2, date: '2011-12-25', race_name: '有馬記念', grade: 'G1', position: 1, jockey: '池添謙一', time: '2:30.5', distance: '2500m', course: '中山', prize: 300000000 },
      { id: 3, date: '2012-06-24', race_name: '宝塚記念', grade: 'G1', position: 1, jockey: '池添謙一', time: '2:10.8', distance: '2200m', course: '阪神', prize: 110000000 },
    ]
  },
  {
    id: 3,
    name: 'ジェンティルドンナ',
    name_en: 'Gentildonna',
    born_year: 2009,
    sex: '牝',
    color: '鹿毛',
    status: '繁殖牝馬',
    farm: 'ノーザンファーム',
    birthplace: '北海道安平町',
    trainer: '石坂正',
    stable: '栗東',
    owner: '(有)サンデーレーシング',
    jockey: '岩田康誠',
    sire: 'ディープインパクト',
    dam: 'ドナブリーニ',
    sire_of_sire: 'サンデーサイレンス',
    dam_of_sire: 'ウインドインハーヘア',
    sire_of_dam: 'Bertolini',
    dam_of_dam: "Moonlight's Box",
    best_time: '2:23.6',
    best_distance: '2400m',
    best_race: 'ジャパンカップ',
    earnings: 1168800000,
    g1_wins: 7,
    win_rate: 58,
    record: { wins: 14, losses: 4, places: 2 },
    titles: ['優駿牝馬', '秋華賞', 'ジャパンカップ(2回)', '天皇賞（秋）', 'ドバイシーマクラシック', '有馬記念'],
    races: [
      { id: 1, date: '2012-10-14', race_name: '秋華賞', grade: 'G1', position: 1, jockey: '岩田康誠', time: '1:58.2', distance: '2000m', course: '京都', prize: 75000000 },
      { id: 2, date: '2012-11-25', race_name: 'ジャパンカップ', grade: 'G1', position: 1, jockey: '岩田康誠', time: '2:23.6', distance: '2400m', course: '東京', prize: 250000000 },
    ]
  },
  {
    id: 4,
    name: 'キタサンブラック',
    name_en: 'Kitasan Black',
    born_year: 2012,
    sex: '牡',
    color: '鹿毛',
    status: '種牡馬',
    farm: '大野ファーム',
    birthplace: '北海道新冠町',
    trainer: '清水久詞',
    stable: '栗東',
    owner: '北島三郎',
    jockey: '武豊',
    sire: 'ブラックタイド',
    dam: 'シュガーハート',
    sire_of_sire: 'サンデーサイレンス',
    dam_of_sire: 'ウインドインハーヘア',
    sire_of_dam: 'Sakura Bakushin O',
    dam_of_dam: 'カーリーエンジェル',
    best_time: '2:24.0',
    best_distance: '2400m',
    best_race: 'ジャパンカップ',
    earnings: 1884364000,
    g1_wins: 7,
    win_rate: 67,
    record: { wins: 12, losses: 5, places: 3 },
    titles: ['菊花賞', '天皇賞（春）(2回)', '有馬記念(2回)', 'ジャパンカップ', '大阪杯'],
    races: [
      { id: 1, date: '2015-10-25', race_name: '菊花賞', grade: 'G1', position: 1, jockey: '北村宏司', time: '3:03.9', distance: '3000m', course: '京都', prize: 130000000 },
      { id: 2, date: '2016-04-17', race_name: '天皇賞（春）', grade: 'G1', position: 1, jockey: '武豊', time: '3:14.7', distance: '3200m', course: '京都', prize: 130000000 },
    ]
  },
  {
    id: 5,
    name: 'アーモンドアイ',
    name_en: 'Almond Eye',
    born_year: 2015,
    sex: '牝',
    color: '鹿毛',
    status: '繁殖牝馬',
    farm: 'ノーザンファーム',
    birthplace: '北海道安平町',
    trainer: '国枝栄',
    stable: '美浦',
    owner: '(有)シルクレーシング',
    jockey: 'C.ルメール',
    sire: 'ロードカナロア',
    dam: 'フサイチパンドラ',
    sire_of_sire: 'キングカメハメハ',
    dam_of_sire: 'Invincible Spirit',
    sire_of_dam: 'サンデーサイレンス',
    dam_of_dam: 'Danseur Fabuleux',
    best_time: '1:57.8',
    best_distance: '2000m',
    best_race: '天皇賞（秋）',
    earnings: 1936814600,
    g1_wins: 9,
    win_rate: 75,
    record: { wins: 11, losses: 3, places: 1 },
    titles: ['桜花賞', '優駿牝馬', '秋華賞', 'ジャパンカップ(2回)', '天皇賞（秋）(2回)', 'ドバイターフ', 'ヴィクトリアマイル'],
    races: [
      { id: 1, date: '2018-04-08', race_name: '桜花賞', grade: 'G1', position: 1, jockey: 'C.ルメール', time: '1:33.1', distance: '1600m', course: '阪神', prize: 75000000 },
      { id: 2, date: '2018-05-20', race_name: '優駿牝馬', grade: 'G1', position: 1, jockey: 'C.ルメール', time: '2:23.8', distance: '2400m', course: '東京', prize: 150000000 },
      { id: 3, date: '2018-10-14', race_name: '秋華賞', grade: 'G1', position: 1, jockey: 'C.ルメール', time: '1:56.3', distance: '2000m', course: '京都', prize: 75000000 },
      { id: 4, date: '2018-11-25', race_name: 'ジャパンカップ', grade: 'G1', position: 1, jockey: 'C.ルメール', time: '2:20.6', distance: '2400m', course: '東京', prize: 250000000 },
    ]
  },
  {
    id: 6,
    name: 'コントレイル',
    name_en: 'Contrail',
    born_year: 2017,
    sex: '牡',
    color: '青鹿毛',
    status: '種牡馬',
    farm: 'ノーザンファーム',
    birthplace: '北海道安平町',
    trainer: '矢作芳人',
    stable: '栗東',
    owner: '前田晋二',
    jockey: 'C.ルメール',
    sire: 'ディープインパクト',
    dam: 'ロードクロノス',
    sire_of_sire: 'サンデーサイレンス',
    dam_of_sire: 'ウインドインハーヘア',
    sire_of_dam: "Unbridled's Song",
    dam_of_dam: 'Pretend',
    best_time: '2:24.1',
    best_distance: '2400m',
    best_race: 'ジャパンカップ',
    earnings: 980570000,
    g1_wins: 8,
    win_rate: 80,
    record: { wins: 8, losses: 1, places: 2 },
    titles: ['皐月賞', '日本ダービー', '菊花賞', '大阪杯', 'ジャパンカップ'],
    races: [
      { id: 1, date: '2020-04-19', race_name: '皐月賞', grade: 'G1', position: 1, jockey: '福永祐一', time: '1:57.8', distance: '2000m', course: '中山', prize: 97000000 },
      { id: 2, date: '2020-05-31', race_name: '日本ダービー', grade: 'G1', position: 1, jockey: '福永祐一', time: '2:24.1', distance: '2400m', course: '東京', prize: 200000000 },
      { id: 3, date: '2020-10-25', race_name: '菊花賞', grade: 'G1', position: 1, jockey: '福永祐一', time: '3:00.7', distance: '3000m', course: '京都', prize: 130000000 },
    ]
  },
  {
    id: 7,
    name: 'エフフォーリア',
    name_en: 'Efforia',
    born_year: 2018,
    sex: '牡',
    color: '黒鹿毛',
    status: '現役',
    farm: '社台ファーム',
    birthplace: '北海道千歳市',
    trainer: '鹿戸雄一',
    stable: '美浦',
    owner: '(有)シルクレーシング',
    jockey: '横山武史',
    sire: 'エピファネイア',
    dam: 'ケイティーズハート',
    sire_of_sire: 'シンボリクリスエス',
    dam_of_sire: 'スペシャルウィーク',
    sire_of_dam: "Heart's Cry",
    dam_of_dam: 'Lady Marian',
    best_time: '1:57.9',
    best_distance: '2000m',
    best_race: '天皇賞（秋）',
    earnings: 741100000,
    g1_wins: 3,
    win_rate: 50,
    record: { wins: 6, losses: 4, places: 1 },
    titles: ['皐月賞', '天皇賞（秋）', '有馬記念'],
    races: [
      { id: 1, date: '2021-04-18', race_name: '皐月賞', grade: 'G1', position: 1, jockey: '横山武史', time: '1:57.9', distance: '2000m', course: '中山', prize: 97000000 },
      { id: 2, date: '2021-10-31', race_name: '天皇賞（秋）', grade: 'G1', position: 1, jockey: '横山武史', time: '1:57.9', distance: '2000m', course: '東京', prize: 195000000 },
      { id: 3, date: '2021-12-26', race_name: '有馬記念', grade: 'G1', position: 1, jockey: '横山武史', time: '2:30.5', distance: '2500m', course: '中山', prize: 311000000 },
    ]
  },
  {
    id: 8,
    name: 'イクイノックス',
    name_en: 'Equinox',
    born_year: 2019,
    sex: '牡',
    color: '鹿毛',
    status: '種牡馬',
    farm: 'ノーザンファーム',
    birthplace: '北海道安平町',
    trainer: '木村哲也',
    stable: '美浦',
    owner: '(有)シルクレーシング',
    jockey: 'C.ルメール',
    sire: 'キタサンブラック',
    dam: 'シルヴァーサニー',
    sire_of_sire: 'ブラックタイド',
    dam_of_sire: 'シュガーハート',
    sire_of_dam: 'Silver Deputy',
    dam_of_dam: 'Gold Land',
    best_time: '1:55.2',
    best_distance: '2000m',
    best_race: '天皇賞（秋）',
    earnings: 2048559600,
    g1_wins: 7,
    win_rate: 78,
    record: { wins: 7, losses: 1, places: 2 },
    titles: ['天皇賞（秋）(2回)', '有馬記念', 'ドバイシーマクラシック', 'ジャパンカップ'],
    races: [
      { id: 1, date: '2022-10-30', race_name: '天皇賞（秋）', grade: 'G1', position: 1, jockey: 'C.ルメール', time: '1:56.1', distance: '2000m', course: '東京', prize: 195000000 },
      { id: 2, date: '2022-12-25', race_name: '有馬記念', grade: 'G1', position: 1, jockey: 'C.ルメール', time: '2:29.5', distance: '2500m', course: '中山', prize: 311000000 },
      { id: 3, date: '2023-10-29', race_name: '天皇賞（秋）', grade: 'G1', position: 1, jockey: 'C.ルメール', time: '1:55.2', distance: '2000m', course: '東京', prize: 195000000 },
    ]
  },
  {
    id: 9,
    name: 'リバティアイランド',
    name_en: 'Liberty Island',
    born_year: 2020,
    sex: '牝',
    color: '黒鹿毛',
    status: '現役',
    farm: 'ノーザンファーム',
    birthplace: '北海道安平町',
    trainer: '中内田充正',
    stable: '栗東',
    owner: '(有)サンデーレーシング',
    jockey: '川田将雅',
    sire: 'ドゥラメンテ',
    dam: 'ヤンキーローズ',
    sire_of_sire: 'キングカメハメハ',
    dam_of_sire: 'アドマイヤグルーヴ',
    sire_of_dam: 'All American',
    dam_of_dam: 'Naturalize',
    best_time: '1:32.4',
    best_distance: '1600m',
    best_race: '桜花賞',
    earnings: 584470000,
    g1_wins: 4,
    win_rate: 73,
    record: { wins: 8, losses: 2, places: 1 },
    titles: ['阪神ジュベナイルフィリーズ', '桜花賞', '優駿牝馬', '秋華賞'],
    races: [
      { id: 1, date: '2023-04-09', race_name: '桜花賞', grade: 'G1', position: 1, jockey: '川田将雅', time: '1:32.4', distance: '1600m', course: '阪神', prize: 75000000 },
      { id: 2, date: '2023-05-21', race_name: '優駿牝馬', grade: 'G1', position: 1, jockey: '川田将雅', time: '2:23.1', distance: '2400m', course: '東京', prize: 150000000 },
    ]
  },
  {
    id: 10,
    name: 'ドウデュース',
    name_en: 'Do Deuce',
    born_year: 2019,
    sex: '牡',
    color: '鹿毛',
    status: '現役',
    farm: '追分ファーム',
    birthplace: '北海道日高町',
    trainer: '友道康夫',
    stable: '栗東',
    owner: '(株)キャロットファーム',
    jockey: '武豊',
    sire: 'ハーツクライ',
    dam: 'ダストアンドダイヤモンズ',
    sire_of_sire: 'サンデーサイレンス',
    dam_of_sire: 'アイリッシュダンス',
    sire_of_dam: 'Vindication',
    dam_of_dam: 'Dusty Diva',
    best_time: '2:21.9',
    best_distance: '2400m',
    best_race: '日本ダービー',
    earnings: 874640000,
    g1_wins: 4,
    win_rate: 63,
    record: { wins: 7, losses: 3, places: 3 },
    titles: ['朝日杯フューチュリティS', '日本ダービー', '有馬記念', '天皇賞（秋）'],
    races: [
      { id: 1, date: '2022-05-29', race_name: '日本ダービー', grade: 'G1', position: 1, jockey: '武豊', time: '2:21.9', distance: '2400m', course: '東京', prize: 200000000 },
      { id: 2, date: '2023-12-24', race_name: '有馬記念', grade: 'G1', position: 1, jockey: '武豊', time: '2:33.5', distance: '2500m', course: '中山', prize: 311000000 },
    ]
  },
];

export const getHorseById = (id) => mockHorses.find(h => h.id === parseInt(id));

export const getRelatedHorses = (horse) => {
  const sameFarm = mockHorses.filter(h => h.id !== horse.id && h.farm === horse.farm).slice(0, 3);
  const sameTrainer = mockHorses.filter(h => h.id !== horse.id && h.trainer === horse.trainer).slice(0, 3);
  const sameSire = mockHorses.filter(h => h.id !== horse.id && h.sire === horse.sire).slice(0, 3);
  return { sameFarm, sameTrainer, sameSire };
};
